---
all:
  children:
    f5:
      hosts:
        f5-lab-primary:
          ansible_host: 10.69.238.201
          ansible_user: admin
          ansible_password: Nomios2025
          ansible_connection: httpapi
          ansible_network_os: f5networks.f5_modules.bigip
          ansible_httpapi_use_ssl: yes
          ansible_httpapi_validate_certs: no
          f5_partition: Common
        f5-lab-secondary:
          ansible_host: 10.69.238.204
          ansible_user: admin
          ansible_password: Nomios2024
          ansible_connection: httpapi
          ansible_network_os: f5networks.f5_modules.bigip
          ansible_httpapi_use_ssl: yes
          ansible_httpapi_validate_certs: no
          f5_partition: Common
